import Head from "next/head";
import Navbar from "../../components/Navbar";
import SocialButton from "../../components/SocialButton";
import DribbbleIcon from "../../public/dribbble.svg";
import InstagramIcon from "../../public/instagram.svg";
import TwitterIcon from "../../public/twitter.svg";
import LinkedInIcon from "../../public/linkedin.svg";
import ProjectPreview from "../../components/ProjectPreview";

export default function Home() {
  return (
    <>
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4">
        <div className="flex flex-col gap-16 md:h-[30rem] h-auto bg-[url('/gradient-bg.jpg')] bg-cover p-10 rounded-3xl">
          <h1 className="text-4xl font-semibold">
            Greetings! I&apos;m{" "}
            <span className="bg-gradient-to-r from-blue-400 via-green-400 to-indigo-400 text-transparent bg-clip-text">
              Mohammed Anwar-Sadat Mamudu
            </span>{" "}
            ,a budding full-stack developer with more than 3 years of hands-on
            experience.
          </h1>
          <p className="flex-1">
            I weave code to create seamless digital experiences, blending
            front-end finesse with back-end wizardry. Let&apos;s build something
            awesome together! #WebDeveloper #FullStackJourney
          </p>
          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <a href="mailto:anwarsadat.d2@gmail.com">
              <button className="bg-black text-white font-medium rounded-full py-3 px-12 w-60 lg:w-auto hover:bg-zinc-800 hover:scale-105 transition duration-400 ease-out">
                Contact Me
              </button>
            </a>
            <div className="flex gap-4">
              {/* <SocialButton bgColor="dribble" link="">
                <DribbbleIcon className="w-6 h-6" />
              </SocialButton>
              <SocialButton bgColor="instagram" link="">
                <InstagramIcon className="w-6 h-6" />
              </SocialButton>

              <SocialButton bgColor="twitter" link="">
                <TwitterIcon className="w-6 h-6" />
              </SocialButton> */}

              <SocialButton
                bgColor="linkedin"
                link="https://www.linkedin.com/in/mohammed-anwar-sadat-mamudu-863907246/">
                <LinkedInIcon className="w-6 h-6" />
              </SocialButton>
            </div>
          </div>
        </div>
        <div className="h-[30rem] rounded-3xl bg-[url('/profile.jpg')] bg-cover p-8 bg-center border-2 border-zinc-200" />
      </section>

      <section className="grid grid-cols-1 lg:grid-cols-2 gap-4 my-4">
        <ProjectPreview
          link="https://streamarvel.vercel.app/"
          name="Marvel OTT App"
          description="NextJS, Tailwind, Prisma with MongoDB, NextAuth, Redis + Upstash - Caching"
          imageUrl="/MacStudio.png"
          bgColor="#f58e5b"
          dark
        />
        <ProjectPreview
          link="https://minimalist-watch.netlify.app/"
          name="Minimalist Watch- Frontend"
          description="Vanilla Javascript, HTML, Tailwind"
          imageUrl="/minimalist_watch.png"
          bgColor="#9ef564"
          dark
        />
        {/* <ProjectPreview
          name="Project 2"
          description="Project 2 Description"
          imageUrl="/project-2.png"
          bgColor="#f2e257"
        /> */}
        <ProjectPreview
          link="https://framer-motion-three.vercel.app/"
          name="Framer Motion"
          description="NextJS, Tailwind, FramerMotion"
          imageUrl="/Framer.png"
          bgColor="#f545a0"
          dark
        />
        <ProjectPreview
          link="https://develcorner.netlify.app/"
          name="DevelCorner- Frontend"
          description="ReactJS, Bootstrap"
          imageUrl="/EcomFront.png"
          bgColor="#64f5df"
          dark
        />

        {/* <ProjectPreview
          name="Project 4"
          description="Project 4 Description"
          imageUrl="/project-2.png"
          bgColor="#f58e5b"
          dark
        /> */}
        {/* <ProjectPreview
          name="Project 5"
          description="Project 5 Description"
          imageUrl="/project-1.png"
          bgColor="#64f5df"
        />
        <ProjectPreview
          name="Project 6"
          description="Project 6 Description"
          imageUrl="/project-2.png"
          bgColor="#9ef564"
        /> */}
      </section>
    </>
  );
}
